//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Brayden
{
    public partial class Enchantment
    {
        protected global::System.Web.UI.WebControls.Panel mainPanel;
        protected global::System.Web.UI.WebControls.Repeater categoryRepeater;
        protected global::System.Web.UI.WebControls.Button btnAddNew;
        protected global::System.Web.UI.WebControls.Panel contentPanel;
        protected global::System.Web.UI.WebControls.Image imgDetailLarge;
        protected global::System.Web.UI.WebControls.Label lblDetailName;
        protected global::System.Web.UI.WebControls.Label lblDetailCategory;
        protected global::System.Web.UI.WebControls.Label lblDetailMaxLevel;
        protected global::System.Web.UI.WebControls.Literal litLevelPips;
        protected global::System.Web.UI.WebControls.Label lblDetailName2;
        protected global::System.Web.UI.WebControls.Label lblDetailDesc;
        protected global::System.Web.UI.WebControls.Label lblDetailApplies;
        protected global::System.Web.UI.WebControls.Label lblDetailConflicts;
        protected global::System.Web.UI.WebControls.Label lblDetailTreasure;
        protected global::System.Web.UI.WebControls.Label lblBackMaxLevel;
        protected global::System.Web.UI.WebControls.Literal litDetailContent;
        protected global::System.Web.UI.WebControls.Panel pnlAdminActions;
        protected global::System.Web.UI.WebControls.Button btnEditEnchant;
        protected global::System.Web.UI.WebControls.LinkButton btnDeleteEnchant;
        protected global::System.Web.UI.WebControls.Repeater paginationRepeater;
        protected global::System.Web.UI.WebControls.Repeater rptComments;
        protected global::System.Web.UI.WebControls.Panel pnlAddComment;
        protected global::System.Web.UI.WebControls.TextBox txtComment;
        protected global::System.Web.UI.WebControls.Button btnSubmitComment;
        protected global::System.Web.UI.WebControls.Literal litVisitorMsg;
        protected global::System.Web.UI.WebControls.Panel emptyPanel;
        protected global::System.Web.UI.WebControls.Panel editPanel;
        protected global::System.Web.UI.WebControls.Label lblEditError;
        protected global::System.Web.UI.WebControls.TextBox txtEditName;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditCategory;
        protected global::System.Web.UI.WebControls.TextBox txtEditMaxLevel;
        protected global::System.Web.UI.WebControls.TextBox txtEditThumbnail;
        protected global::System.Web.UI.WebControls.TextBox txtEditDetailImage;
        protected global::System.Web.UI.WebControls.TextBox txtEditDesc;
        protected global::System.Web.UI.WebControls.TextBox txtEditApplies;
        protected global::System.Web.UI.WebControls.TextBox txtEditConflicts;
        protected global::System.Web.UI.WebControls.TextBox txtEditContent;
        protected global::System.Web.UI.WebControls.CheckBox chkEditTreasure;
        protected global::System.Web.UI.WebControls.Panel addPanel;
        protected global::System.Web.UI.WebControls.Label lblAddError;
        protected global::System.Web.UI.WebControls.TextBox txtAddName;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddCategory;
        protected global::System.Web.UI.WebControls.TextBox txtAddMaxLevel;
        protected global::System.Web.UI.WebControls.TextBox txtAddThumbnail;
        protected global::System.Web.UI.WebControls.TextBox txtAddDetailImage;
        protected global::System.Web.UI.WebControls.TextBox txtAddDesc;
        protected global::System.Web.UI.WebControls.TextBox txtAddApplies;
        protected global::System.Web.UI.WebControls.TextBox txtAddConflicts;
        protected global::System.Web.UI.WebControls.TextBox txtAddContent;
        protected global::System.Web.UI.WebControls.CheckBox chkAddTreasure;
    }
}
