//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Brayden
{
    public partial class Potion
    {
        protected global::System.Web.UI.WebControls.Panel mainPanel;
        protected global::System.Web.UI.WebControls.Repeater categoryRepeater;
        protected global::System.Web.UI.WebControls.Button btnAddNew;
        protected global::System.Web.UI.WebControls.Panel contentPanel;
        protected global::System.Web.UI.WebControls.Image imgDetailLarge;
        protected global::System.Web.UI.WebControls.Label lblDetailName;
        protected global::System.Web.UI.WebControls.Label lblDetailCategory;
        protected global::System.Web.UI.WebControls.Label lblDetailType;
        protected global::System.Web.UI.WebControls.Label lblFrontDuration;
        protected global::System.Web.UI.WebControls.Image imgIngredient;
        protected global::System.Web.UI.WebControls.Label lblBackName;
        protected global::System.Web.UI.WebControls.Label lblDetailEffect;
        protected global::System.Web.UI.WebControls.Label lblDetailDesc;
        protected global::System.Web.UI.WebControls.Label lblDetailDuration;
        protected global::System.Web.UI.WebControls.Label lblBackType;
        protected global::System.Web.UI.WebControls.Label lblDetailBase;
        protected global::System.Web.UI.WebControls.Label lblDetailIngredient;
        protected global::System.Web.UI.WebControls.Literal litDetailContent;
        protected global::System.Web.UI.WebControls.Panel pnlAdminActions;
        protected global::System.Web.UI.WebControls.Button btnEditPotion;
        protected global::System.Web.UI.WebControls.LinkButton btnDeletePotion;
        protected global::System.Web.UI.WebControls.Repeater paginationRepeater;
        protected global::System.Web.UI.WebControls.Repeater rptComments;
        protected global::System.Web.UI.WebControls.Panel pnlAddComment;
        protected global::System.Web.UI.WebControls.TextBox txtComment;
        protected global::System.Web.UI.WebControls.Button btnSubmitComment;
        protected global::System.Web.UI.WebControls.Literal litVisitorMsg;
        protected global::System.Web.UI.WebControls.Panel emptyPanel;
        protected global::System.Web.UI.WebControls.Panel editPanel;
        protected global::System.Web.UI.WebControls.Label lblEditError;
        protected global::System.Web.UI.WebControls.TextBox txtEditName;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditType;
        protected global::System.Web.UI.WebControls.TextBox txtEditDuration;
        protected global::System.Web.UI.WebControls.TextBox txtEditEffect;
        protected global::System.Web.UI.WebControls.TextBox txtEditBase;
        protected global::System.Web.UI.WebControls.TextBox txtEditIngredient;
        protected global::System.Web.UI.WebControls.TextBox txtEditDesc;
        protected global::System.Web.UI.WebControls.TextBox txtEditThumbnail;
        protected global::System.Web.UI.WebControls.TextBox txtEditDetailImage;
        protected global::System.Web.UI.WebControls.TextBox txtEditIngredientImage;
        protected global::System.Web.UI.WebControls.TextBox txtEditContent;
        protected global::System.Web.UI.WebControls.Panel addPanel;
        protected global::System.Web.UI.WebControls.Label lblAddError;
        protected global::System.Web.UI.WebControls.TextBox txtAddName;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddType;
        protected global::System.Web.UI.WebControls.TextBox txtAddDuration;
        protected global::System.Web.UI.WebControls.TextBox txtAddEffect;
        protected global::System.Web.UI.WebControls.TextBox txtAddBase;
        protected global::System.Web.UI.WebControls.TextBox txtAddIngredient;
        protected global::System.Web.UI.WebControls.TextBox txtAddDesc;
        protected global::System.Web.UI.WebControls.TextBox txtAddThumbnail;
        protected global::System.Web.UI.WebControls.TextBox txtAddDetailImage;
        protected global::System.Web.UI.WebControls.TextBox txtAddIngredientImage;
        protected global::System.Web.UI.WebControls.TextBox txtAddContent;
    }
}
